--oauth2-client-id=77185425430.apps.googleusercontent.com
--oauth2-client-secret=OTJgUOQcT7lO7GsGZq2G4IlT
--enable-features=AllowLegacyMV2Extensions
--disable-features=PrintCompositorLPAC,ExtensionManifestV2Unsupported,ExtensionManifestV2Disabled
--disk-cache-dir=/run/user/0/chromium-cache
