call plug#begin('~/.vim/plugged')
Plug 'scrooloose/syntastic'
"Plug 'bling/vim-airline'
"Plug 'scrooloose/nerdcommenter'
Plug 'Valloric/youcompleteme', { 'do': './install.py --clang-completer' }
call plug#end()

source ~/git/cwee-config-files/vim/autoexec.vim
