
# for use when splitting files
export FAT32_NBYTES=4294967295

alias sl='ls'
alias grep='grep -n --color'
alias diff='diff -u --color'
alias xopen=xdg-open
alias tmux='TERM=xterm-256color tmux'
eval "$(thefuck --alias fk)"

alias rt-private='rtorrent -n -o import=~/.rt-private.rc'

bindkey "^[[A" history-beginning-search-backward
bindkey "^[[B" history-beginning-search-forward

if [[ -f ~/.fzf.zsh  ]]; then
	export FZF_DEFAULT_COMMAND='rg --files --no-ignore --hidden --follow --glob "!.git/*"'
	source ~/.fzf.zsh
fi
